### Запрос на создание нового пароля
POST http://localhost:8080/api/auth/reset-password
Content-Type: application/json

{
  "token": "42aNUBxUk29TSOk1GM56IANtL8KL6yh_Fmi31w5OMRY",
  "password": "123456",
  "passwordConfirmation": "123456"
}